language: php

php:
  - 5.6
  - 7.0
  - 7.1

before_script:
  - composer install

script:
  - composer build

after_script:
- php vendor/bin/coveralls -v

notifications:
  irc:
    channels:
      - "chat.freenode.net#honeybee"
    on_success: always
    on_failure: always
    use_notice: false
    skip_join: false